= Implementing scopes 

//Exercise #3

The OAuth 2.0 https://tools.ietf.org/html/rfc6749#page-23[scopes] make it so you can further limit access to something protected by OAuth. You have the ability of control by defining words, such as `READ` and `WRITE` or others that you might want that might be more specific like `CONTRATOR`, `PUBLIC`, `EMPLOYEES_ONLY`, and etc.. And you can put them in four different places, like…:

* In the universal set definition that is called `defaultScopes` and that is where you define all of the possible scopes you might want:
+
[source,xml,linenums]
----
<oauth2-provider:config
  scopes="CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE
     defaultScope"CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE"
 > ...
/oath2-provider:config>
----
+
* Another place is in `/validate` validation endpoint, to enforce a particular subset of all of the scoped previously defined.
* Also the Mule OAuth 2.0 Access Token Enforcement policy. Enforce scopes by specifying a space-separated list.
+
When specifying more than one scope, it enforces the `OR` logic. In the case that the token to be validated is assocciated with one, two, or more the requested scopes, the policy validates it successfully.

As follows, example of scopes in Mule 4.2.x or larger:

[source,xml,linenums]
----
...
<oauth2-provider:config name="external-oauth2-provider"
resourceOwnerSecurityProvider="resourceOwnerSeurityProvider"
clientSecurityProvider="clientSecurityProvider"
supportedGrantTypes="AUTHORIZATION_CODE,IMPLICIT,RESOURCE_OWNER_PASSWORD_CREDENTIALS,CLIENT_CREDENTIALS"
listenerConfig="https.listener"
scopes="CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE"
    defaultScope"CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE"
clientStore="clientObjectStore">
<oauth2-provider:token-config path="/access-token" tokenTtl="5" tokenTtlTimeUnit="SECONDS" tokenStore="tokenObjectStore">
<oauth2-provider:refresh-token-strategy>
<oauth2-provider:single-refresh-token objectStore="refreshTokenObjectStore"/>
    </oauth2-provider:refresh-toke-strategy>
    </oauth2-provider:token-config>
    <oauth2-provider:authorization-config path="/authorize" authorizationCodeStore="authorizationCodeObjectStore"/>
    </oauth2-provider:config>
...
----

If you are still confused, you can go see https://anypoint.mulesoft.com/exchange/org.mule.templates/api-gateway-oauth2-provider/[Mule OAuth 2.0 server for Anypoint platform].
